### ISSUE TITLE
김승규 - 3주차 미션 - github issue 

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [wanted-internship-11th-team10/pre-onboarding-11th-3-10#1]
## UI
<img width="500" alt="ss" src="https://github.com/wanted-internship-11th-team10/pre-onboarding-11th-3-10/assets/45627868/2ef03022-1e6a-4e18-a7ed-03e26ea260b3">

### ISSUE LIST
<img width="500" alt="sss" src="https://github.com/wanted-internship-11th-team10/pre-onboarding-11th-3-10/assets/45627868/901bff95-dd31-4dd3-85a7-2c1a77b7f963">

## TODO
1.  공통 헤더
    - [ ] 두 페이지는 공통 헤더를 공유합니다.
    - [ ] 헤더에는 Organization Name / Repository Name이 표시됩니다.
2.  이슈 목록 화면
    - [ ] 이슈 목록 가져오기 API 활용
    - [ ] open 상태의 이슈 중 코멘트가 많은 순으로 정렬
    - [ ] 각 행에는 ‘이슈번호, 이슈제목, 작성자, 작성일, 코멘트수’를 표시
    - [ ] 다섯번째 셀에는 광고 이미지 출력
        - [ ] 광고 이미지 출력
        - [ ] 광고 이미지 클릭 시 https://www.wanted.co.kr/ 로 이동
    - [ ] 화면을 아래로 스크롤 할 시 이슈 목록 추가 로딩(인피니티 스크롤)
3. 이슈 상세 화면
    - [ ] 이슈의 상세 내용 표시
    - [ ]  ‘이슈번호, 이슈제목, 작성자, 작성일, 코멘트 수, 작성자 프로필 이미지, 본문' 표시
4. 데이터 요청 중 로딩 표시
    - [ ]  데이터 요청 중 로딩 표시
5. 에러 화면 구현
     - [ ] 404 not found page
     - [ ] 각 페이지(리스트, 상세페이지) 에러 화면 <- 고민중...
6. 지정된 조건(open 상태, 코멘트 많은 순)에 맞게 데이터 요청 및 표시
     - [ ] open 상태이고 코멘트 많은 순 으로 데이터 표시
     - [ ] 조건을 수정할 수 있는 UI ????
